/can_interface_node:
  ros__parameters:
    topics:
      joy: "/joy"
      pwm: "/gripper_pwm"
      join_state: "/join_state_gripper"


    pwm:
      gain: 200 # value range: pwm_idle +/- pwm_gain
      idle: 1500
    can:
      interface: "can0"
      
